### ISSUE TITLE
What is the motivation for this fork?

### ISSUE THREAD

**Issue by rootulp** [ZondaX/hid#13]
Silly question but I see this repo is a fork of https://github.com/karalabe/hid. What is the motivation for it? When should zondax/hid be used instead of karalabe/hid?

It would help if the README explained the rationale for the fork.

**Comment by rootulp** [comment]
Tagging @jleni @ftheirs for input.

**Comment by jleni** [comment]
This was the original fix that triggered the fork
https://github.com/Zondax/hid/commit/2684efe91edc1d3dadf1b20481f67fc2b887b744

It required quick action and later multiple projects started to use the fork.
We currently looking at migrating some of them to another new library or going back upstream.
